server:
  port: 8080

spring:
  application:
    name: ${APP_FILE_NAME:api-gateway}
  cloud:
    gateway:
      routes:
        - id: product-service
          uri: ${PRODUCT_SERVICE_URL:http://localhost:8081}
          predicates:
            - Path= /api-product/** , /product/v3/api-docs/**
          filters:
            - RewritePath=/api-product/(?<remaining>.*), /$\{remaining}

        - id: stock-service
          uri: ${STOCK_SERVICE_URL:http://localhost:8082}
          predicates:
            - Path= /api-stock/** , /stock/v3/api-docs/**
          filters:
            - RewritePath=/api-stock/(?<remaining>.*), /$\{remaining}

        - id: order-service
          uri: ${ORDER_SERVICE_URL:http://localhost:8083}
          predicates:
            - Path= /api-order/** , /order/v3/api-docs/**
          filters:
            - RewritePath=/api-order/(?<remaining>.*), /$\{remaining}

logging:
  level:
    reactor.netty: INFO