spring:
  application:
    name: product
  profiles:
    include: postgresql

springdoc:
  swagger-ui:
    path: /swagger-ui

server:
  port: 8081

logging:
  level:
    org.hibernate: INFO
    reactor.netty: INFO

service-address:
  stock: ${STOCK_SERVICE_URL:http://localhost:8082}
  order: ${ORDER_SERVICE_URL:http://localhost:8083}

