spring:
    application:
        name: product
    profiles:
        include: postgresql

springdoc:
    swagger-ui:
        path: /swagger-ui

server:
    port: 8081

logging:
    level:
        org.hibernate: INFO

service-address:
    stock: http://localhost:8082
    order: http://localhost:8083
