spring:
  application:
    name: order
  profiles:
    include: postgresql

springdoc:
  swagger-ui:
    path: /swagger-ui

server:
  port: 8083

logging:
  level:
    org.hibernate: INFO

service-address:
  product: ${PRODUCT_SERVICE_URL:http://localhost:8081}
  stock: ${STOCK_SERVICE_URL:http://localhost:8082}
