spring:
  application:
    name: stock
  profiles:
    include: postgresql

springdoc:
  swagger-ui:
    path: /swagger-ui

server:
  port: 8083

logging:
  level:
    org.hibernate: INFO

service-address:
  product: http://localhost:8081
  stock: http://localhost:8082