spring:
  application:
    name: stock
  profiles:
    include: postgresql

springdoc:
  swagger-ui:
    path: /swagger-ui

server:
  port: 8082

logging:
  level:
    org.hibernate: INFO

service-address:
  product: ${PRODUCT_SERVICE_URL:http://localhost:8081}
  order: ${ORDER_SERVICE_URL:http://localhost:8083}